# Generated by Django 2.0.5 on 2018-05-24 08:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('yellowant_api', '0002_yellowantredirectstate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Awsec2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AWS_APIAccessKey', models.CharField(max_length=100)),
                ('AWS_APISecretAccess', models.CharField(max_length=100)),
                ('user_integration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yellowant_api.UserIntegration')),
            ],
        ),
    ]
