# Generated by Django 2.0.5 on 2018-05-24 11:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('yellowant_api', '0005_auto_20180524_1129'),
    ]

    operations = [
        migrations.CreateModel(
            name='ec2cred',
            fields=[
                ('id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='yellowant_api.UserIntegration')),
                ('AWS_APIAccessKey', models.CharField(max_length=100)),
                ('AWS_APISecretAccess', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='ec2credentials',
            name='id',
        ),
        migrations.DeleteModel(
            name='ec2credentials',
        ),
    ]
