# Generated by Django 2.0.5 on 2018-05-24 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yellowant_api', '0006_auto_20180524_1131'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ec2cred',
            name='id',
        ),
        migrations.DeleteModel(
            name='ec2cred',
        ),
    ]
