# Generated by Django 2.0.5 on 2018-05-24 11:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('yellowant_api', '0007_auto_20180524_1136'),
    ]

    operations = [
        migrations.CreateModel(
            name='awsec2',
            fields=[
                ('id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='yellowant_api.UserIntegration')),
                ('AWS_APIAccessKey', models.CharField(max_length=100)),
                ('AWS_APISecretAccess', models.CharField(max_length=100)),
            ],
        ),
    ]
