# Generated by Django 2.0.5 on 2018-05-25 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yellowant_api', '0008_awsec2'),
    ]

    operations = [
        migrations.AddField(
            model_name='awsec2',
            name='AWS_update_login_flag',
            field=models.BooleanField(default=False, max_length=2),
        ),
    ]
