# Generated by Django 2.0.5 on 2018-05-29 12:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('yellowant_api', '0009_awsec2_aws_update_login_flag'),
    ]

    operations = [
        migrations.CreateModel(
            name='awss3',
            fields=[
                ('id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='yellowant_api.UserIntegration')),
                ('AWS_APIAccessKey', models.CharField(max_length=100)),
                ('AWS_APISecretAccess', models.CharField(max_length=100)),
                ('AWS_update_login_flag', models.BooleanField(default=False, max_length=2)),
            ],
        ),
        migrations.RemoveField(
            model_name='awsec2',
            name='id',
        ),
        migrations.DeleteModel(
            name='awsec2',
        ),
    ]
