# Generated by Django 2.0.5 on 2018-06-26 10:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('yellowant_api', '0011_auto_20180613_1226'),
    ]

    operations = [
        migrations.CreateModel(
            name='spotify',
            fields=[
                ('id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='yellowant_api.UserIntegration')),
                ('access_token', models.CharField(max_length=100)),
                ('refresh_token', models.CharField(max_length=100)),
                ('update_login_flag', models.BooleanField(default=False, max_length=2)),
            ],
        ),
        migrations.RemoveField(
            model_name='awss3',
            name='id',
        ),
        migrations.DeleteModel(
            name='awss3',
        ),
    ]
