# Generated by Django 2.0.5 on 2018-06-28 06:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('yellowant_api', '0012_auto_20180626_1038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yellowantredirectstate',
            name='id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='yellowant_api.UserIntegration'),
        ),
    ]
