# Generated by Django 2.0.5 on 2018-06-28 06:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('yellowant_api', '0013_auto_20180628_0620'),
    ]

    operations = [
        migrations.CreateModel(
            name='spotifyRedirectState',
            fields=[
                ('user_integration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='yellowant_api.UserIntegration')),
                ('state', models.CharField(max_length=512)),
            ],
        ),
        migrations.AlterField(
            model_name='yellowantredirectstate',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
