# Generated by Django 2.0.5 on 2018-06-28 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yellowant_api', '0014_auto_20180628_0644'),
    ]

    operations = [
        migrations.RenameField(
            model_name='spotifyredirectstate',
            old_name='user_integration',
            new_name='id',
        ),
    ]
