# Generated by Django 2.0.5 on 2018-06-28 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yellowant_api', '0015_auto_20180628_0652'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spotify',
            name='access_token',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='spotify',
            name='refresh_token',
            field=models.CharField(max_length=250),
        ),
    ]
